### ISSUE TITLE
No thumbnails visible in grid

### ISSUE THREAD

**Issue by edwin-oetelaar** [forrest79/StaticNginxGallery#1]
Installed it.
Have a working /thumbnails/ the image filter is ok.

URL is : https://dmx.e3n.nl/

The images are not shown in grid view.
Did I forget anything?
- what info do you need?
- Ubuntu 20.04 with node.js 1.18
- nginx reports no errors

**Comment by forrest79** [comment]
Do you see any errors in the browser dev console - network tab? There should be one request for every thumbnail.

**Comment by edwin-oetelaar** [comment]
No errors in the dev console.
Also no requests for the thumbnail images.
No references in the html to a thumbnail image

Switched on the server again : you can try now.
https://dmx.e3n.nl/

the yaml config contains :
thumbnails: true # bool - yes/no or string with cache directory

**Comment by forrest79** [comment]
Thanks for a working example - it looks like a bug when I can't detect upper cased file extensions. I will release a fix this week.

**Comment by edwin-oetelaar** [comment]
thanks for figuring this out.

here is a patch

diff --git a/src/templates/xslt.ejs b/src/templates/xslt.ejs
index 6ec4c37..1838485 100644
--- a/src/templates/xslt.ejs
+++ b/src/templates/xslt.ejs
@@ -51,7 +51,7 @@

            </svg>

    </a>

</xsl:when>
-
<xsl:when test="contains(' .jpg .gif .png ', concat(' ', substring(.,
string-length() - 3), ' ')) or contains(' .webp ', concat(' ', substring(.,
string-length() - 4), ' '))">
+
<xsl:when test="contains(' .jpg .gif .png .JPG .GIF .PNG ', concat(' ',
substring(., string-length() - 3), ' ')) or contains(' .webp ', concat(' ',
substring(., string-length() - 4), ' '))">

    <a href="{.}" class="glightbox" data-type="image" data-title="{.}">

            <img src="<% if (typeof thumbnails === 'string') { %><%= path
%>/cache/thumbnails{$processedUri}<% } else if (thumbnails) { %><%= path
%>/thumbnails{$processedUri}<% } %>{.}" alt="{.}" loading="lazy" />

    </a>

**Comment by forrest79** [comment]
Thanks, I prepared a little bit more universal fix (extensions are compared case insensitive), it's in the master.

**Comment by edwin-oetelaar** [comment]
yes this the better generic fix.
Handles cases like Image.Jpeg also.
