### ISSUE TITLE
Suggestion: Create thumbnail from mp4 with ffmpeg

### ISSUE THREAD

**Issue by moom0o** [forrest79/StaticNginxGallery#2]
I'd like to leave a suggestion, mp4's don't have any thumbnails so I manually grabbed the thumbnails of my videos with ffmpeg using the command below.
```for f in *; do ffmpeg -i "$f" -vcodec mjpeg -vframes 1 -an -f rawvideo -ss `ffmpeg -i $f 2>&1 | grep Duration | awk '{print $2}' | tr -d , | awk -F ':' '{print ($3+$2*60+$1*3600)/2}'` $f.jpg; done```

It would be great if this was added for others to use, would probably only work well when cached however.

**Comment by forrest79** [comment]
Hi, thanks for the `ffmpeg` command. Originally I was thinking of using `ffmpeg` to generate video thumbnails. To keep it simple, I decided to skip it but I will try to add an option to generate this (and cache it), it should be really handy.

**Comment by forrest79** [comment]
Hi, I added optional cached thumbnail generator via ffmpeg. It's in the master, you can test it. Feel free to open new issue if something goes wrong.
